---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: route-whisperer-tls
  labels:
    app: route-whisperer-webhook-server
  name: route-whisperer-webhook-server
  namespace: route-whisperer
spec:
  ports:
    - name: pywsgi
      port: 8443
      protocol: TCP
      targetPort: pywsgi
  selector:
    app: route-whisperer-webhook-server
