---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - configmap.yaml
  - daemonset.yaml
  - namespace.yaml
  - rolebinding.yaml
  - scc-clusterrole.yaml
  - scc-rolebinding.yaml
  - scc.yaml
  - serviceaccount.yaml
